before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
language: python
python:
- '3.5'
install:
- pip install .
- pip install codecov
- pip install pytest-cov
script:
- py.test --cov=./
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)